[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vates"
version = "0.1.0"
description = "Python actuarial model"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    {name = "Shanya Shi", email = "shanyashi2025@gmail.com"}
]
keywords = ["actuarial model", "asset-liability model", "alm"]
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.3.0, <3.0.0",
    "scipy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["vates*"]
